#!/bin/bash

# decompress only
for target in "@" ; do
    echo $target
    if [ ${target: -4:4} = '.zip' ]; then
        unzip -q "$target" && rm "$target"
    else
        tar -xf "$target" && rm "$target"
    fi
done
